# GitHub Sponsors funding configuration file
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository for details

github: [AbinVarghexe]
# patreon: abinvarghese
# ko_fi: abinvarghese
# custom: ['https://paypal.me/your_paypal_username', 'https://buymeacoffee.com/your_username']
